// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarK64.Models.EF;

#nullable disable

namespace SolarK64.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004085106_create_new_database")]
    partial class create_new_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarK64.Models.Entities.KieuPhanHoi", b =>
                {
                    b.Property<string>("MaKieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKieu");

                    b.ToTable("KieuPhanHoi");
                });

            modelBuilder.Entity("SolarK64.Models.Entities.PhanHoi", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KieuPhanHoiMaKieu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKieuPhanHoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Uid");

                    b.HasIndex("KieuPhanHoiMaKieu");

                    b.HasIndex("MaKieuPhanHoi");

                    b.ToTable("PhanHoi");
                });

            modelBuilder.Entity("SolarK64.Models.Entities.PhanHoi", b =>
                {
                    b.HasOne("SolarK64.Models.Entities.KieuPhanHoi", "KieuPhanHoi")
                        .WithMany()
                        .HasForeignKey("KieuPhanHoiMaKieu");

                    b.HasOne("SolarK64.Models.Entities.KieuPhanHoi", null)
                        .WithMany()
                        .HasForeignKey("MaKieuPhanHoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KieuPhanHoi");
                });
#pragma warning restore 612, 618
        }
    }
}
